version: '3'
services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - mynetwork

  mongodb:
    image: mongo
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    networks:
      - mynetwork  

# 定義自定義網絡 mynetwork
networks:
  mynetwork: